Temporary disable clang-7 on Linux due to clang-internal issue:
In file included from
cppinsights/AutoStmtHandler.h:11:
In file included from /usr/lib/llvm-7/include/clang/AST/AST.h:18:
In file included from /usr/lib/llvm-7/include/clang/AST/ASTContext.h:18:
In file included from
/usr/lib/llvm-7/include/clang/AST/ASTTypeTraits.h:20:
In file included from /usr/lib/llvm-7/include/clang/AST/Decl.h:17:
In file included from /usr/lib/llvm-7/include/clang/AST/APValue.h:17:
In file included from /usr/lib/llvm-7/include/clang/Basic/LLVM.h:22:
In file included from /usr/lib/llvm-7/include/llvm/Support/Casting.h:18:
/usr/lib/llvm-7/include/llvm/Support/Compiler.h:524:30: error: no member
named 'align_val_t' in namespace 'std'
                        std::align_val_t(Alignment)
                        ~~~~~^
/usr/lib/llvm-7/include/llvm/Support/Compiler.h:544:26: error: no member
named 'align_val_t' in namespace 'std'
                    std::align_val_t(Alignment)
                    ~~~~~^